envVarGroups:
  - name: databases
    envVars:
      - key : TEST
        value: test-value
      
databases:
  - name: temporal-core
    # Core state db
    postgresMajorVersion: '17' 
    region: frankfurt
    plan: free
    databaseName: temporal
    user: temporal
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

services:
  # PG Bouncer. Should be private but not supported in free plan
  - type: pserv
    name: pgbouncerff
    runtime: docker
    # NOTE: service in != regions can't communicate privately ?
    region: frankfurt
    plan: standard
    # TODO: Should be pinned to a version
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  temporal-core
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50

  - type: web
    # This is the visibility DB
    name: elasticsearch
    region: frankfurt
    plan: standard
    runtime: docker
    disk:
      name: esdata
      mountPath: /usr/share/elasticsearch/data
      sizeGB: 5
    repo: https://github.com/rbpartC/elasticsearch
    envVars:
      - fromGroup: temporal
      - key: discovery.type
        value: single-node
      - key: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"
      - key: ELASTIC_PASSWORD
        generateValue: true
  
  - type: pserv
    name: temporal
    autoDeploy: false
    plan: starter
    region: frankfurt
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
    - key: SERVICES
      value: frontend,matching,history,worker
    - key: DYNAMIC_CONFIG_FILE_PATH
      value: /etc/temporal/dynamicconfig.yaml
    - key: BIND_ON_IP
      value: 0.0.0.0
    - key: TEMPORAL_BROADCAST_ADDRESS
      value: 0.0.0.0
    - key: TEMPORAL_CLI_ADDRESS
      value: localhost:7233
    - key: SKIP_POSTGRES_DB_CREATION
      value: "true"
    - key: DB
      value: postgresql
    - key: DBNAME
      fromDatabase:
        name: temporal-core
        property: database
    - key: DB_PORT
      fromDatabase:
        name: temporal-core
        property: port
    - key: POSTGRES_USER
      fromDatabase:
        name: temporal-core
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: temporal-core
        property: password
    - key: POSTGRES_SEEDS
      fromDatabase:
        name: temporal-core
        property: host
    - key: VISIBILITY_DBNAME
      fromService:
        name: elasticsearch
        type: web
        property: database
    - key: VISIBILITY_DB_PORT
      fromService:
        name: elasticsearch
        type: web
        property: port
    - key: VISIBILITY_POSTGRES_USER
      fromService:
        name: elasticsearch
        type: web
        property: user
    - key: VISIBILITY_POSTGRES_PWD
      fromService:
        name: elasticsearch
        type: web
        property: password
    - key: VISIBILITY_POSTGRES_SEEDS
      fromService:
        name: elasticsearch
        type: web
        property: host
  
  - type: web
    name: temporal-ui
    autoDeploy: false
    plan: starter
    region: frankfurt
    runtime: docker
    dockerfilePath: ./web/Dockerfile
    envVars:
    - key: PORT
      value: 8088
    - key: TEMPORAL_PERMIT_WRITE_API
      value: "true"
    - key: TEMPORAL_GRPC_HOST
      fromService:
        name: temporal
        type: pserv
        property: host

  - type: worker
    repo: https://github.com/render-examples/sample-temporal-app
    name: app-worker
    plan: starter
    region: frankfurt
    runtime: go
    buildCommand: go build worker/main.go
    startCommand: ./main
    envVars:
    - key: TEMPORAL_CLUSTER_HOST
      fromService:
        name: temporal
        type: pserv
        property: host