envVarGroups:
  - name: elasticsearch
    envVars:
    - key: ELASTIC_USERNAME
      value: elastic
    - key: ELASTIC_PASSWORD
      generateValue: true
    - key: ES_PORT
      value: "9200"
    - key: ES_TRANSPORT_PORT
      value: "9300"
  - name: temporal-shared
    envVars:
    - key: SQL_CONNECT_ATTRIBUTES
      value: "binary_parameters=yes"
    - key: DYNAMIC_CONFIG_FILE_PATH
      value: /etc/temporal/dynamicconfig_es.yaml
    - key: ENABLE_ES
      value: "true"
    - key: ES_VERSION
      value: v7
    - key: DB
      value: postgresql
    - key: FRONTEND_GRPC_PORT
      value: "7233"
    - key: FRONTEND_MEMBERSHIP_PORT
      value: "6933"
    - key: HISTORY_GRPC_PORT
      value: "7234"
    - key: HISTORY_MEMBERSHIP_PORT
      value: "6934"
    - key: MATCHING_GRPC_PORT
      value: "7235"
    - key: MATCHING_MEMBERSHIP_PORT
      value: "6935"
    - key: WORKER_GRPC_PORT
      value: "7239"
    - key: WORKER_MEMBERSHIP_PORT
      value: "6939"
    - key: LOG_LEVEL
      value: info
    - key: NUM_HISTORY_SHARDS
      value: "4"
    - key: SQL_MAX_CONNS
      value: "20"
    - key: SQL_MAX_IDLE_CONNS
      value: "20"
    - key: SQL_MAX_CONN_TIME
      value: 1h
    - key: SQL_TLS_ENABLED
      value: "false"
    - key: SQL_CA
      value: ""
    - key: SQL_CERT
      value: ""
    - key: SQL_CERT_KEY
      value: ""
    - key: SQL_HOST_VERIFICATION
      value: "false"
    - key: SQL_HOST_NAME
      value: ""
    - key: ES_SCHEME
      value: http
    - key: ES_VIS_INDEX
      value: temporal_visibility_v1_dev
    - key: TEMPORAL_BROADCAST_ADDRESS
      value: ""
    - key: PPROF_PORT
      value: "0"
    - key: TEMPORAL_TLS_REFRESH_INTERVAL
      value: "0s"
    - key: TEMPORAL_TLS_EXPIRATION_CHECKS_WARNING_WINDOW
      value: "0s"
    - key: TEMPORAL_TLS_EXPIRATION_CHECKS_ERROR_WINDOW
      value: "0s"
    - key: TEMPORAL_TLS_EXPIRATION_CHECKS_CHECK_INTERVAL
      value: "0s"
    - key: TEMPORAL_TLS_REQUIRE_CLIENT_AUTH
      value: "false"
    - key: TEMPORAL_TLS_SERVER_CERT
      value: ""
    - key: TEMPORAL_TLS_SERVER_KEY
      value: ""
    - key: TEMPORAL_TLS_SERVER_CERT_DATA
      value: ""
    - key: TEMPORAL_TLS_SERVER_KEY_DATA
      value: ""
    - key: TEMPORAL_TLS_INTERNODE_SERVER_NAME
      value: ""
    - key: TEMPORAL_TLS_INTERNODE_DISABLE_HOST_VERIFICATION
      value: "false"
    - key: TEMPORAL_TLS_FRONTEND_CERT
      value: ""
    - key: TEMPORAL_TLS_FRONTEND_KEY
      value: ""
    - key: TEMPORAL_TLS_FRONTEND_CERT_DATA
      value: ""
    - key: TEMPORAL_TLS_FRONTEND_KEY_DATA
      value: ""
    - key: TEMPORAL_TLS_FRONTEND_SERVER_NAME
      value: ""
    - key: TEMPORAL_TLS_FRONTEND_DISABLE_HOST_VERIFICATION
      value: "false"
    - key: TEMPORAL_JWT_KEY_REFRESH
      value: 1m
    - key: TEMPORAL_JWT_PERMISSIONS_CLAIM
      value: permissions
    - key: TEMPORAL_AUTH_AUTHORIZER
      value: ""
    - key: TEMPORAL_AUTH_CLAIM_MAPPER
      value: ""
    - key: BIND_ON_IP
      value: "0.0.0.0"

databases:
  - name: temporal-core
    # Core state db
    postgresMajorVersion: '17' 
    region: frankfurt
    plan: free
    databaseName: temporal
    user: temporal
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

services:
  # PG Bouncer. Should be private but not supported in free plan
  - type: pserv
    name: pgbouncerff
    runtime: docker
    # NOTE: service in != regions can't communicate privately ?
    region: frankfurt
    plan: standard
    # TODO: Should be pinned to a version
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  temporal-core
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50

  # Elasticsearch for visibility
  - type: pserv
    # This is the visibility DB
    name: elasticsearch
    region: frankfurt
    plan: standard
    runtime: docker
    disk:
      name: esdata
      mountPath: /usr/share/elasticsearch/data
      sizeGB: 5
    repo: https://github.com/rbpartC/elasticsearch
    envVars:
      - fromGroup: elasticsearch
      - key: discovery.type
        value: single-node
      - key: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"

  # Admin tools - to suspend after migrations
  - type: worker
    name: admin-tools
    autoDeploy: false
    plan: starter
    region: frankfurt
    runtime: image
    image:
      url: temporalio/admin-tools:1.28
    envVars:
    - key: DBNAME
      fromDatabase:
        name: temporal-core
        property: database
    - key: POSTGRES_USER
      fromDatabase:
        name: temporal-core
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: temporal-core
        property: password
    - key: POSTGRES_SEEDS
      fromService:
        name: pgbouncerff
        property: host
        type: pserv
    - key: DB_PORT
      fromDatabase:
        name: temporal-core
        property: port
    - key: ES_SEEDS
      fromService:
        name: elasticsearch
        type: pserv
        property: host
    - fromGroup: elasticsearch
  
  # Frontend service
  - type: pserv
    name: temporal-frontend
    autoDeploy: false
    plan: starter
    region: frankfurt
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
    - key : PORT
      value: "7233"
    - fromGroup: temporal-shared
    - key: SERVICES
      value: frontend
    - key: ES_SEEDS
      fromService:
        name: elasticsearch
        type: pserv
        property: host
    - fromGroup: elasticsearch
    - key: DBNAME
      fromDatabase:
        name: temporal-core
        property: database
    - key: DB_PORT
      fromDatabase:
        name: temporal-core
        property: port
    - key: POSTGRES_USER
      fromDatabase:
        name: temporal-core
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: temporal-core
        property: password
    - key: POSTGRES_SEEDS
      fromService:
        name: pgbouncerff
        property: host
        type: pserv

  # History service
  - type: pserv
    name: temporal-history
    autoDeploy: false
    plan: starter
    region: frankfurt
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
    - fromGroup: temporal-shared
    - key: SERVICES
      value: history
    - key: TEMPORAL_FRONTEND_HOST
      fromService:
        name: temporal-frontend
        type: pserv
        property: host
    - key: ES_SEEDS
      fromService:
        name: elasticsearch
        type: pserv
        property: host
    - fromGroup: elasticsearch
    - key: DBNAME
      fromDatabase:
        name: temporal-core
        property: database
    - key: POSTGRES_USER
      fromDatabase:
        name: temporal-core
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: temporal-core
        property: password
    - key: POSTGRES_SEEDS
      fromService:
        name: pgbouncerff
        property: host
        type: pserv
    - key: DB_PORT
      fromDatabase:
        name: temporal-core
        property: port

  # Matching service
  - type: pserv
    name: temporal-matching
    autoDeploy: false
    plan: starter
    region: frankfurt
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
    - fromGroup: temporal-shared
    - key: SERVICES
      value: matching
    - key: TEMPORAL_FRONTEND_HOST
      fromService:
        name: temporal-frontend
        type: pserv
        property: host
    - key: ES_SEEDS
      fromService:
        name: elasticsearch
        type: pserv
        property: host
    - fromGroup: elasticsearch
    - key: DBNAME
      fromDatabase:
        name: temporal-core
        property: database
    - key: POSTGRES_USER
      fromDatabase:
        name: temporal-core
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: temporal-core
        property: password
    - key: POSTGRES_SEEDS
      fromService:
        name: pgbouncerff
        property: host
        type: pserv
    - key: DB_PORT
      fromDatabase:
        name: temporal-core
        property: port

  # Worker service - performs maintenance tasks
  - type: worker
    name: temporal-worker
    autoDeploy: false
    plan: starter
    region: frankfurt
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
    - fromGroup: temporal-shared
    # The worker service needs to wait for the history service to be up first,
    # otherwise it will fail with "error starting scanner".
    - key: DEPENDS_ON_HISTORY
      fromService:
        name: temporal-history
        type: pserv
        property: host
    - key: SERVICES
      value: worker
    - key: TEMPORAL_FRONTEND_HOST
      fromService:
        name: temporal-frontend
        type: pserv
        property: host
    - key: ES_SEEDS
      fromService:
        name: elasticsearch
        type: pserv
        property: host
    - fromGroup: elasticsearch
    - key: DBNAME
      fromDatabase:
        name: temporal-core
        property: database
    - key: POSTGRES_USER
      fromDatabase:
        name: temporal-core
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: temporal-core
        property: password
    - key: POSTGRES_SEEDS
      fromService:
        name: pgbouncerff
        property: host
        type: pserv
    - key: DB_PORT
      fromDatabase:
        name: temporal-core
        property: port

  # Temporal UI      
  - type: web
    name: temporal-ui
    autoDeploy: false
    plan: starter
    region: frankfurt
    runtime: docker
    dockerfilePath: ./web/Dockerfile
    envVars:
    - key: PORT
      # For render
      value: 8080
    - key: TEMPORAL_UI_PORT
      # For temporal
      value: 8080
    - key: TEMPORAL_PERMIT_WRITE_API
      value: "true"
    - key: TEMPORAL_GRPC_HOST
      fromService:
        name: temporal-frontend
        type: pserv
        property: host

  # Demo python worker with example workflows
  - type: worker
    name: temporal-python-worker
    plan: starter
    region: frankfurt
    runtime: docker
    dockerfilePath: ./temporal-workflows/Dockerfile
    envVars:
    - key: TEMPORAL_GRPC_HOST
      fromService:
        name: temporal-frontend
        type: pserv
        property: host
    - fromGroup: temporal-shared
