envVarGroups:
  - name: temporal
    envVars:
      - key : TEST
        value: test-value
      
databases:
  - name: temporal-db 
    postgresMajorVersion: '17' 
    region: frankfurt
    plan: free
    databaseName: temporaldb
    user: temporaldbuser
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

services:
  # PG Bouncer. Should be private but not supported in free plan
  - type: web
    name: pgbouncer
    runtime: docker
    region: frankfurt
    plan: free
    repo: https://github.com/render-oss/docker-pgbouncer
    # TODO: Should be pinned to a version
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  temporal-db
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50

  - type: web
    name: elasticsearch
    region: frankfurt
    plan: starter
    runtime: docker
    disk:
      name: esdata
      mountPath: /usr/share/elasticsearch/data
      sizeGB: 5
    image: 
      url: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    envVars:
      - fromGroup: temporal
      - key: discovery.type
        value: single-node
      - key: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"


