apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rbpartC/stackai-challenge
    path: dev/temporal-stack
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
