apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
spec:
  ports:
    - port: 8080
  selector:
    app: temporal-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: {{ .Values.ui.image }}
          env:
            - name: TEMPORAL_ADDRESS
              value: "{{ .Values.temporal.frontend.host }}:{{ .Values.temporal.frontend.port }}"
            - name: TEMPORAL_UI_PORT
              value: {{ .Values.ui.port | quote }}
          ports:
            - containerPort: {{ .Values.ui.port }}
