on: [push]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    needs: precommit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r temporal-workflows/requirements.txt
          pip install pytest pytest-asyncio pytest-cov

      - name: Run tests with coverage
        run: |
          PYTHONPATH=temporal-workflows/app pytest --cov=temporal-workflows/app --cov-report=xml --cov-report=term temporal-workflows/tests

      - name: Save coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage.xml

      - name: Run security scan with Bandit
        run: |
          pip install bandit
          bandit -r temporal-workflows/app -f xml -o bandit-report.xml || true

      - name: Save security scan report artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: ./bandit-report.xml